### ISSUE TITLE
Panic when running on a virtual device

### ISSUE THREAD

**Issue by otavio** [UpdateHub/updatehub#73]
In the validation process, I got a panic as below:

```
panic: runtime error: integer divide by zero        

goroutine 10 [running]:   
panic(0x6c3d40, 0xc42000c0d0)                       
        .../usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/UpdateHub/updatehub/updatehub.(*PollState).Handle.func1(0xc4200e4000, 0xc420078780, 0xc4200de400)
        .../github.com/UpdateHub/updatehub/updatehub/states.go:245 +0x24f
created by github.com/UpdateHub/updatehub/updatehub.(*PollState).Handle                                  
        .../github.com/UpdateHub/updatehub/updatehub/states.go:257 +0x90
```

**Comment by otavio** [comment]
Fixed in #75
